#!/bin/bash
MACHINE_CERT=/usr/local/share/ca-certificates
MY_CERT_NAME=dev.local.crt

DEV_MACHINE_CERT_FOLDER=$MACHINE_CERT/localDev
DEV_MACHINE_CERT_FOLDER_AND_FILE_NAME=$DEV_MACHINE_CERT_FOLDER/$MY_CERT_NAME
MY_CERT_FULL_PATH_AND_NAME=`pwd`/$MY_CERT_NAME

# Enable cert in host
sudo mkdir -p $DEV_MACHINE_CERT_FOLDER
sudo chmod 755 $DEV_MACHINE_CERT_FOLDER
sudo touch $DEV_MACHINE_CERT_FOLDER_AND_FILE_NAME
sudo chmod 777 $DEV_MACHINE_CERT_FOLDER_AND_FILE_NAME
sudo cat $MY_CERT_FULL_PATH_AND_NAME > $DEV_MACHINE_CERT_FOLDER_AND_FILE_NAME
sudo chmod 644 $DEV_MACHINE_CERT_FOLDER_AND_FILE_NAME
sudo update-ca-certificates
